pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: git-configurations
  - group: docker-configurations

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
    displayName: 'Install Java17'
  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: $(knownHosts)
      sshPublicKey: $(publicKey)
      sshKeySecureFile: 'id_rsa'
    displayName: 'Install SSH'
  - script: |
      mvn clean test
    displayName: 'Validate project & run tests'

  - script: |
      mvn package 
      ls -l ./target
    displayName: 'Create JAR'

  - script: |
      docker --version
      docker ps
      docker build --tag issue_ticket_tracker:0.0.1 .
      docker images | grep issue
    displayName: 'Create docker image'

  - script: |
      docker tag issue_ticket_tracker:0.0.1 adamsz1/issue_ticket_tracker:0.0.1
      docker login docker.io -u $(dockerhubUsername) -p $(dockerhubPassword)
      docker push adamsz1/issue_ticket_tracker:0.0.1
    displayName: 'Push docker image'
